name: vitalinea
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  firebase_auth: ^3.4.1
  firebase_core: ^1.19.1
  google_maps_flutter: ^2.1.8
  geolocator: ^9.0.0
  permission_handler: ^10.0.0
  cloud_firestore: ^3.3.0
  rflutter_alert: ^2.0.4
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/markers/abn.bmp
    - assets/markers/abp.bmp
    - assets/markers/an.bmp
    - assets/markers/ap.bmp
    - assets/markers/bn.bmp
    - assets/markers/bp.bmp
    - assets/markers/on.bmp
    - assets/markers/op.bmp
    - assets/markers/my.bmp
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/Montserrat-Medium.ttf
        - asset: assets/Montserrat-Bold.ttf
        - asset: assets/Montserrat-MediumItalic.ttf
        - asset: assets/Montserrat-BoldItalic.ttf
        - asset: assets/Montserrat-Regular.ttf
        - asset: assets/Montserrat-Italic.ttf
        - asset: assets/Montserrat-Thin.ttf
        - asset: assets/Montserrat-ThinItalic.ttf
